[package]
name = "jj-bond"
version = "0.1.6"
edition = "2024"
description = "jujutsu TUI"
documentation = "https://github.com/TD-Sky/jj-bond"
repository = "https://github.com/TD-Sky/jj-bond"
readme = "README.md"
categories = ["command-line-interface"]
keywords = ["jujutsu", "jj", "tui", "terminal"]
license = "MIT"
include = [
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "templates/**/*",
  "build.rs",
]

[dependencies]
thiserror = "2"
ratatui = "0.30"
ratzgo = "0.1.2"
compio = { version = "0.19", features = ["runtime", "process", "time"] }
futures-util = "0.3"
enumflags2 = "0.7.12"
ansi-to-tui = "8.0"
smol_str = "0.3"
thin-cell = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing-appender = "0.2.5"
dirs = "6"
notify = "8.2"
regex = "1.13"
ratatui-textarea = "0.9"
tui-tree-widget = "0.24"
bytestring = "1.5"
serde = { version = "1.0", features = ["derive"] }
toml = "1.1.4+spec-1.1.0"
eros = "0.7"
clap = { version = "4.6", features = ["derive"] }
constcat = "0.6"
mimalloc = "0.1"

[build-dependencies]
vergen-gix = { version = "10.0", features = ["build"] }

[lints.clippy]
module_inception = "allow"

[[bin]]
name = "jb"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
