global = [
  { key = "1", desc = "select Log tab" },
  { key = "2", desc = "select Bookmarks tab" },
  { key = "3", desc = "select Tags tab" },
  { key = "4", desc = "select Operations tab" },
  { key = "H", desc = "previous tab" },
  { key = "L", desc = "next tab" },
  { key = "q", desc = "quit" }
]

log-history = [
  { key = "k", desc = "up" },
  { key = "j", desc = "down" },
  { key = "<C-d>", desc = "scroll down 50%" },
  { key = "<C-u>", desc = "scroll up 50%" },
  { key = "<C-f>", desc = "page down" },
  { key = "<C-b>", desc = "page up" },
  { key = "<Enter>", desc = "show change" },
  { key = "<Esc>", desc = "cancel yank / reset Log mode" },
  { key = "n", desc = "new child change" },
  { key = "e", desc = "edit change" },
  { key = "d", desc = "describe / duplicate yanked" },
  { key = "u", desc = "undo" },
  { key = "<C-r>", desc = "redo" },
  { key = "<Space>", desc = "yank change / range" },
  { key = "r", desc = "rebase yanked here" },
  { key = "a", desc = "abandon change" },
  { key = "s", desc = "squash change" },
  { key = "x", desc = "split change" },
  { key = "X", desc = "split change parallelly" },
  { key = "f", desc = "fetch" },
  { key = "b", desc = "open bookmark list" },
  { key = "t", desc = "open tag list" },
  { key = "p", desc = "push" },
  { key = "?", desc = "help" },
]

log-history-show = [
  { key = "k", desc = "history up" },
  { key = "j", desc = "history down" },
  { key = "<C-d>", desc = "history scroll down 50%" },
  { key = "<C-u>", desc = "history scroll up 50%" },
  { key = "<C-f>", desc = "history page down" },
  { key = "<C-b>", desc = "history page up" },
  { key = "K", desc = "show scroll up" },
  { key = "J", desc = "show scroll down" },
  { key = "<Enter>", desc = "open files|diff" },
  { key = "<Esc>", desc = "back to history" },
  { key = "n", desc = "new child change" },
  { key = "e", desc = "edit change" },
  { key = "d", desc = "describe / duplicate yanked" },
  { key = "u", desc = "undo" },
  { key = "<C-r>", desc = "redo" },
  { key = "<Space>", desc = "yank change / range" },
  { key = "r", desc = "rebase yanked here" },
  { key = "a", desc = "abandon change" },
  { key = "s", desc = "squash change" },
  { key = "x", desc = "split change" },
  { key = "X", desc = "split change parallelly" },
  { key = "f", desc = "fetch" },
  { key = "b", desc = "open bookmark list" },
  { key = "t", desc = "open tag list" },
  { key = "p", desc = "push" },
  { key = "?", desc = "help" },
]

log-files-diff = [
  { key = "k", desc = "file up" },
  { key = "j", desc = "file down" },
  { key = "<C-d>", desc = "files scroll down 50%" },
  { key = "<C-u>", desc = "files scroll up 50%" },
  { key = "<C-f>", desc = "files page down" },
  { key = "<C-b>", desc = "files page up" },
  { key = "<Enter>", desc = "open diff" },
  { key = "<Esc>", desc = "back to history|show" },
  { key = "?", desc = "help" }
]

log-diff = [
  { key = "k", desc = "diff scroll up" },
  { key = "j", desc = "diff scroll down" },
  { key = "<C-d>", desc = "diff scroll down 50%" },
  { key = "<C-u>", desc = "diff scroll up 50%" },
  { key = "<C-f>", desc = "diff page down" },
  { key = "<C-b>", desc = "diff page up" },
  { key = "<Esc>", desc = "back to files|diff" },
  { key = "?", desc = "help" }
]

log-tag-list = [
  { key = "k", desc = "up" },
  { key = "j", desc = "down" },
  { key = "<Enter>", desc = "select / create tag" },
  { key = "<Esc>", desc = "close list / cancel input" },
  { key = "<Backspace>", desc = "delete input char" },
  { key = "<C-d>", desc = "scroll down 50%" },
  { key = "<C-u>", desc = "scroll up 50% / clear input" },
  { key = "<C-b>", desc = "page up / cursor left" },
  { key = "<C-f>", desc = "page down / cursor right" },
  { key = "<C-a>", desc = "cursor to start" },
  { key = "<C-e>", desc = "cursor to end" },
  { key = "?", desc = "help" }
]

log-bookmark-list = [
  { key = "k", desc = "up" },
  { key = "j", desc = "down" },
  { key = "<Enter>", desc = "select / create bookmark" },
  { key = "<Esc>", desc = "close list / cancel input" },
  { key = "<Backspace>", desc = "delete input char" },
  { key = "<C-d>", desc = "scroll down 50%" },
  { key = "<C-u>", desc = "scroll up 50% / clear input" },
  { key = "<C-b>", desc = "page up / cursor left" },
  { key = "<C-f>", desc = "page down / cursor right" },
  { key = "<C-a>", desc = "cursor to start" },
  { key = "<C-e>", desc = "cursor to end" },
  { key = "?", desc = "help" }
]

confirm-modal = [
  { key = "y", desc = "confirm" },
  { key = "n", desc = "cancel" },
  { key = "<Esc>", desc = "cancel" },
  { key = "?", desc = "help" }
]

log-unsync = [
  { key = "k", desc = "up" },
  { key = "j", desc = "down" },
  { key = "<C-d>", desc = "scroll down 50%" },
  { key = "<C-u>", desc = "scroll up 50%" },
  { key = "<C-f>", desc = "page down" },
  { key = "<C-b>", desc = "page up" },
  { key = "<Enter>", desc = "push selected bookmark" },
  { key = "<Esc>", desc = "cancel push" },
  { key = "?", desc = "help" }
]

bookmarks-remotes = [
  { key = "k", desc = "up" },
  { key = "j", desc = "down" },
  { key = "<C-d>", desc = "scroll down 50%" },
  { key = "<C-u>", desc = "scroll up 50%" },
  { key = "<C-f>", desc = "page down" },
  { key = "<C-b>", desc = "page up" },
  { key = "<Enter>", desc = "track selected remote" },
  { key = "<Esc>", desc = "cancel track" },
  { key = "?", desc = "help" }
]

bookmarks-tree = [
  { key = "k", desc = "tree up" },
  { key = "j", desc = "tree down" },
  { key = "<C-d>", desc = "tree scroll down 50%" },
  { key = "<C-u>", desc = "tree scroll up 50%" },
  { key = "<C-f>", desc = "tree page down" },
  { key = "<C-b>", desc = "tree page up" },
  { key = "l", desc = "open bookmark node" },
  { key = "h", desc = "close bookmark node" },
  { key = "K", desc = "history scroll up" },
  { key = "J", desc = "history scroll down" },
  { key = "t", desc = "track bookmark" },
  { key = "u", desc = "untrack bookmark" },
  { key = "d", desc = "delete bookmark" },
  { key = "<Enter>", desc = "view history in Log tab" },
  { key = "?", desc = "help" },
]

tags-tree = [
  { key = "k", desc = "tree up" },
  { key = "j", desc = "tree down" },
  { key = "<C-d>", desc = "tree scroll down 50%" },
  { key = "<C-u>", desc = "tree scroll up 50%" },
  { key = "<C-f>", desc = "tree page down" },
  { key = "<C-b>", desc = "tree page up" },
  { key = "l", desc = "open tag node" },
  { key = "h", desc = "close tag node" },
  { key = "K", desc = "history scroll up" },
  { key = "J", desc = "history scroll down" },
  { key = "d", desc = "delete tag" },
  { key = "<Enter>", desc = "view history in Log tab" },
  { key = "?", desc = "help" },
]

operations = [
  { key = "k", desc = "scroll up" },
  { key = "j", desc = "scroll down" },
  { key = "<C-d>", desc = "scroll down 50%" },
  { key = "<C-u>", desc = "scroll up 50%" },
  { key = "<C-f>", desc = "page down" },
  { key = "<C-b>", desc = "page up" },
  { key = "?", desc = "help" }
]

help = [{ key = "k", desc = "up" }, { key = "j", desc = "down" }]
